# Generated by Django 4.0.1 on 2022-01-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='content',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
